from services.shoppinglist import Product
from typing import Protocol, List


class GroceryStore(Protocol):
    async def authenticate(): ...
    async def close(): ...

    async def search(
        self, name_search: str, department_search: str | None = None
    ) -> List[Product]: ...

    async def add_to_cart(self, id: str, amount: int): ...
